package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbBuildingServer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbBuildingServer extends BaseTbBuildingServer<TbBuildingServer> {
	public static final TbBuildingServer dao = new TbBuildingServer().dao();
}
