package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbLicense;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbLicense extends BaseTbLicense<TbLicense> {
	public static final TbLicense dao = new TbLicense().dao();
}
