package com.xiaosong.model;

import com.xiaosong.model.base.BaseTbNetwork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbNetwork extends BaseTbNetwork<TbNetwork> {
	public static final TbNetwork dao = new TbNetwork().dao();
}
