package com.xiaosong.model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbShareroom extends com.xiaosong.model.base.BaseTbShareroom<TbShareroom> {
    public static final TbShareroom dao = new TbShareroom().dao();
}