package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCompanyuser<M extends BaseTbCompanyuser<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setCompanyId(Integer companyId) {
		set("companyId", companyId);
		return (M)this;
	}

	public Integer getCompanyId() {
		return getInt("companyId");
	}

	public M setSectionId(Integer companyId) {
		set("sectionId", companyId);
		return (M)this;
	}

	public Integer getSectionId() {
		return getInt("sectionId");
	}

	public M setUserId(Integer userId) {
		set("userId", userId);
		return (M)this;
	}

	public Integer getUserId() {
		return getInt("userId");
	}

	public M setUserName(String userName) {
		set("userName", userName);
		return (M)this;
	}

	public String getUserName() {
		return getStr("userName");
	}

	public M setReceiveDate(String receiveDate) {
		set("receiveDate", receiveDate);
		return (M)this;
	}

	public String getReceiveDate() {
		return getStr("receiveDate");
	}

	public M setReceiveTime(String receiveTime) {
		set("receiveTime", receiveTime);
		return (M)this;
	}

	public String getReceiveTime() {
		return getStr("receiveTime");
	}

	public M setRoleType(String roleType) {
		set("roleType", roleType);
		return (M)this;
	}

	public String getRoleType() {
		return getStr("roleType");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

	public M setIdType(String idType) {
		set("idType", idType);
		return (M)this;
	}

	public String getIdType() {
		return getStr("idType");
	}

	public M setIdNO(String idNO) {
		set("idNO", idNO);
		return (M)this;
	}

	public String getIdNO() {
		return getStr("idNO");
	}

	public M setCurrentStatus(String currentStatus) {
		set("currentStatus", currentStatus);
		return (M)this;
	}

	public String getCurrentStatus() {
		return getStr("currentStatus");
	}

	public M setIsSued(String isSued) {
		set("isSued", isSued);
		return (M)this;
	}

	public String getIsSued() {
		return getStr("isSued");
	}

	public M setIsDel(String isDel) {
		set("isDel", isDel);
		return (M)this;
	}

	public String getIsDel() {
		return getStr("isDel");
	}

	public M setPhoto(String photo) {
		set("photo", photo);
		return (M)this;
	}

	public String getPhoto() {
		return getStr("photo");
	}

	public M setCompanyFloor(String companyFloor) {
		set("companyFloor", companyFloor);
		return (M)this;
	}

	public String getCompanyFloor() {
		return getStr("companyFloor");
	}

	public M setBid(String bid) {
		set("bid", bid);
		return (M)this;
	}

	public String getBid() {
		return getStr("bid");
	}

	public M setRid(String rid) {
		set("rid", rid);
		return (M)this;
	}

	public String getRid() {
		return getStr("rid");
	}

	public M setCardInfo(Integer cardInfo) {
		set("cardInfo", cardInfo);
		return (M)this;
	}

	public Integer getCardInfo() {
		return getInt("cardInfo");
	}

}
