package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbVisitor<M extends BaseTbVisitor<M>> extends Model<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setVisitorName(String visitorName) {
		set("visitorName", visitorName);
		return (M)this;
	}

	public String getVisitorName() {
		return getStr("visitorName");
	}

	public M setVisitorIdCard(String visitorIdCard) {
		set("visitorIdCard", visitorIdCard);
		return (M)this;
	}

	public String getVisitorIdCard() {
		return getStr("visitorIdCard");
	}

	public M setUserId(String userId) {
		set("userId", userId);
		return (M)this;
	}

	public String getUserId() {
		return getStr("userId");
	}

	public M setSoleCode(String soleCode) {
		set("soleCode", soleCode);
		return (M)this;
	}

	public String getSoleCode() {
		return getStr("soleCode");
	}

	public M setByVisitorName(String byVisitorName) {
		set("byVisitorName", byVisitorName);
		return (M)this;
	}

	public String getByVisitorName() {
		return getStr("byVisitorName");
	}

	public M setByVisitorIdCard(String byVisitorIdCard) {
		set("byVisitorIdCard", byVisitorIdCard);
		return (M)this;
	}

	public String getByVisitorIdCard() {
		return getStr("byVisitorIdCard");
	}

	public M setVisitDate(String visitDate) {
		set("visitDate", visitDate);
		return (M)this;
	}

	public String getVisitDate() {
		return getStr("visitDate");
	}

	public M setVisitTime(String visitTime) {
		set("visitTime", visitTime);
		return (M)this;
	}

	public String getVisitTime() {
		return getStr("visitTime");
	}

	public M setStartDateTime(String startDateTime) {
		set("startDateTime", startDateTime);
		return (M)this;
	}

	public String getStartDateTime() {
		return getStr("startDateTime");
	}

	public M setEndDateTime(String endDateTime) {
		set("endDateTime", endDateTime);
		return (M)this;
	}

	public String getEndDateTime() {
		return getStr("endDateTime");
	}

	public M setOrgCode(String orgCode) {
		set("orgCode", orgCode);
		return (M)this;
	}

	public String getOrgCode() {
		return getStr("orgCode");
	}

	public M setProvince(String province) {
		set("province", province);
		return (M)this;
	}

	public String getProvince() {
		return getStr("province");
	}

	public M setCity(String city) {
		set("city", city);
		return (M)this;
	}

	public String getCity() {
		return getStr("city");
	}

	public M setCreateTime(String createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public String getCreateTime() {
		return getStr("createTime");
	}

	public M setVisitId(String visitId) {
		set("visitId", visitId);
		return (M)this;
	}

	public String getVisitId() {
		return getStr("visitId");
	}

	public M setDelFlag(String delFlag) {
		set("delFlag", delFlag);
		return (M)this;
	}

	public String getDelFlag() {
		return getStr("delFlag");
	}

	public M setIsSued(String isSued) {
		set("isSued", isSued);
		return (M)this;
	}

	public String getIsSued() {
		return getStr("isSued");
	}

	public M setDelPosted(String delPosted) {
		set("delPosted", delPosted);
		return (M)this;
	}

	public String getDelPosted() {
		return getStr("delPosted");
	}

	public M setIsPosted(String isPosted) {
		set("isPosted", isPosted);
		return (M)this;
	}

	public String getIsPosted() {
		return getStr("isPosted");
	}

	public M setPreStartTime(String preStartTime) {
		set("preStartTime", preStartTime);
		return (M)this;
	}

	public String getPreStartTime() {
		return getStr("preStartTime");
	}

	public M setIdFrontImgUrl(String idFrontImgUrl) {
		set("idFrontImgUrl", idFrontImgUrl);
		return (M)this;
	}

	public String getIdFrontImgUrl() {
		return getStr("idFrontImgUrl");
	}

	public M setPhoto(String photo) {
		set("photo", photo);
		return (M)this;
	}

	public String getPhoto() {
		return getStr("photo");
	}

	public M setBid(String bid) {
		set("bid", bid);
		return (M)this;
	}

	public String getBid() {
		return getStr("bid");
	}

	public M setRid(String rid) {
		set("rid", rid);
		return (M)this;
	}

	public String getRid() {
		return getStr("rid");
	}

	public M setCardInfo(Integer cardInfo) {
		set("cardInfo", cardInfo);
		return (M)this;
	}

	public Integer getCardInfo() {
		return getInt("cardInfo");
	}

}
