package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbStatement<M extends com.xiaosong.model.base.BaseTbStatement<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setStaffNowCount(Integer staffNowCount) {
		set("staffNowCount", staffNowCount);
		return (M)this;
	}

	public Integer getStaffNowCount() {
		return getInt("staffNowCount");
	}


	public M setVisitorNowCount(Integer visitorNowCount) {
		set("visitorNowCount", visitorNowCount);
		return (M)this;
	}

	public Integer getVisitorNowCount() {
		return getInt("visitorNowCount");
	}

	public M setStaffCount(Integer staffCount) {
		set("staffCount", staffCount);
		return (M)this;
	}

	public Integer getStaffCount() {
		return getInt("staffCount");
	}

	public M setNowSendSuccessCount(Integer nowSendSuccessCount) {
		set("nowSendSuccessCount", nowSendSuccessCount);
		return (M)this;
	}

	public Integer getNowSendSuccessCount() {
		return getInt("nowSendSuccessCount");
	}

	public M setNowSendFailCount(Integer nowSendFailCount) {
		set("nowSendFailCount", nowSendFailCount);
		return (M)this;
	}

	public Integer getNowSendFailCount() {
		return getInt("nowSendFailCount");
	}

	public M setStaffNowDelCount(Integer staffNowDelCount) {
		set("staffNowDelCount", staffNowDelCount);
		return (M)this;
	}

	public Integer getStaffNowDelCount() {
		return getInt("staffNowDelCount");
	}

	public M setNewDate(String newDate) {
		set("newDate", newDate);
		return (M)this;
	}

	public String getNewDate() {
		return getStr("newDate");
	}

}
