package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbLicense<M extends BaseTbLicense<M>> extends Model<M> implements IBean {

	public M setLicenseId(Integer licenseId) {
		set("licenseId", licenseId);
		return (M)this;
	}

	public Integer getLicenseId() {
		return getInt("licenseId");
	}

	public M setSwjCode(String swjCode) {
		set("swjCode", swjCode);
		return (M)this;
	}

	public String getSwjCode() {
		return getStr("swjCode");
	}

	public M setMac(String mac) {
		set("mac", mac);
		return (M)this;
	}

	public String getMac() {
		return getStr("mac");
	}

	public M setBeginDate(String beginDate) {
		set("beginDate", beginDate);
		return (M)this;
	}

	public String getBeginDate() {
		return getStr("beginDate");
	}

	public M setEndDate(String endDate) {
		set("endDate", endDate);
		return (M)this;
	}

	public String getEndDate() {
		return getStr("endDate");
	}

}
