package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbAccessrecord<M extends BaseTbAccessrecord<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setOrgCode(String orgCode) {
		set("orgCode", orgCode);
		return (M)this;
	}

	public String getOrgCode() {
		return getStr("orgCode");
	}

	public M setPospCode(String pospCode) {
		set("pospCode", pospCode);
		return (M)this;
	}

	public String getPospCode() {
		return getStr("pospCode");
	}

	public M setScanDate(String scanDate) {
		set("scanDate", scanDate);
		return (M)this;
	}

	public String getScanDate() {
		return getStr("scanDate");
	}

	public M setScanTime(String scanTime) {
		set("scanTime", scanTime);
		return (M)this;
	}

	public String getScanTime() {
		return getStr("scanTime");
	}

	public M setTurnOver(String turnOver) {
		set("turnOver", turnOver);
		return (M)this;
	}

	public String getTurnOver() {
		return getStr("turnOver");
	}

	public M setDeviceType(String deviceType) {
		set("deviceType", deviceType);
		return (M)this;
	}

	public String getDeviceType() {
		return getStr("deviceType");
	}

	public M setDeviceIp(String deviceIp) {
		set("deviceIp", deviceIp);
		return (M)this;
	}

	public String getDeviceIp() {
		return getStr("deviceIp");
	}

	public M setUserType(String userType) {
		set("userType", userType);
		return (M)this;
	}

	public String getUserType() {
		return getStr("userType");
	}

	public M setUserName(String userName) {
		set("userName", userName);
		return (M)this;
	}

	public String getUserName() {
		return getStr("userName");
	}

	public M setIdCard(String idCard) {
		set("idCard", idCard);
		return (M)this;
	}

	public String getIdCard() {
		return getStr("idCard");
	}

	public M setCardNO(String cardNO) {
		set("cardNO", cardNO);
		return (M)this;
	}

	public String getCardNO() {
		return getStr("cardNO");
	}

	public M setIsSendFlag(String isSendFlag) {
		set("isSendFlag", isSendFlag);
		return (M)this;
	}

	public String getIsSendFlag() {
		return getStr("isSendFlag");
	}

	public M setTemperature(String Temperature) {
		set("Temperature", Temperature);
		return (M)this;
	}

	public String getTemperature() {
		return getStr("Temperature");
	}

	public M setAbnomal(String Abnomal) {
		set("Abnomal", Abnomal);
		return (M)this;
	}

	public String getAbnomal() {
		return getStr("Abnomal");
	}

	public M setPhoto(String photo) {
		set("photo", photo);
		return (M)this;
	}

	public String getPhoto() {
		return getStr("photo");
	}

}
