package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbDevice<M extends BaseTbDevice<M>> extends Model<M> implements IBean {

	public M setDeviceId(Integer deviceId) {
		set("deviceId", deviceId);
		return (M)this;
	}

	public Integer getDeviceId() {
		return getInt("deviceId");
	}

	public M setDeviceMode(String deviceMode) {
		set("deviceMode", deviceMode);
		return (M)this;
	}

	public String getDeviceMode() {
		return getStr("deviceMode");
	}

	public M setDeviceType(String deviceType) {
		set("deviceType", deviceType);
		return (M)this;
	}

	public String getDeviceType() {
		return getStr("deviceType");
	}

	public M setDeviceIp(String deviceIp) {
		set("deviceIp", deviceIp);
		return (M)this;
	}

	public String getDeviceIp() {
		return getStr("deviceIp");
	}

	public M setDevicePort(Integer devicePort) {
		set("devicePort", devicePort);
		return (M)this;
	}

	public Integer getDevicePort() {
		return getInt("devicePort");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setDeviceName(String deviceName) {
		set("deviceName", deviceName);
		return (M)this;
	}

	public String getDeviceName() {
		return getStr("deviceName");
	}

	public M setDevicePassword(String devicePassword) {
		set("devicePassword", devicePassword);
		return (M)this;
	}

	public String getDevicePassword() {
		return getStr("devicePassword");
	}

}
