package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbNetwork<M extends BaseTbNetwork<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setLocalIp(String localIp) {
		set("localIp", localIp);
		return (M)this;
	}

	public String getLocalIp() {
		return getStr("localIp");
	}

	public M setLocalGetWay(String localGetWay) {
		set("localGetWay", localGetWay);
		return (M)this;
	}

	public String getLocalGetWay() {
		return getStr("localGetWay");
	}

	public M setLocalMask(String localMask) {
		set("localMask", localMask);
		return (M)this;
	}

	public String getLocalMask() {
		return getStr("localMask");
	}

	public M setWifi(String wifi) {
		set("wifi", wifi);
		return (M)this;
	}

	public String getWifi() {
		return getStr("wifi");
	}

	public M setWifiIp(String wifiIp) {
		set("wifiIp", wifiIp);
		return (M)this;
	}

	public String getWifiIp() {
		return getStr("wifiIp");
	}

	public M setWifiGetWay(String wifiGetWay) {
		set("wifiGetWay", wifiGetWay);
		return (M)this;
	}

	public String getWifiGetWay() {
		return getStr("wifiGetWay");
	}

	public M setWifiMask(String wifiMask) {
		set("wifiMask", wifiMask);
		return (M)this;
	}

	public String getWifiMask() {
		return getStr("wifiMask");
	}

}
